package USB2p0_pkg;

    `include "uvm_macros.svh"
     import uvm_pkg::*;
       
 `ifdef UTMI_16BIT
      parameter DATA_WIDTH = 16;
  `else
      parameter DATA_WIDTH = 8;
  `endif


      typedef enum {USB_LS,USB_FS,USB_HS} speed_state;

	`include "../config/enum_defs.sv"
	`include "../agents/USB2p0_sequence_item.sv"
	`include "../agents/USB2p0_phy_sequence_item.sv"
	`include "../config/USB2p0_env_config.sv"

	`include "../agents/host_controller_agent/USB2p0_HOST_controller_sequencer.sv"
	`include "../agents/device_controller_agent/USB2p0_DEVICE_controller_sequencer.sv"
	`include "../agents/phy_agent/USB2p0_PHY_sequencer.sv"

	`include "../agents/host_controller_agent/USB2p0_HOST_controller_driver.sv"
	`include "../agents/device_controller_agent/USB2p0_DEVICE_controller_driver.sv"
	`include "../agents/phy_agent/USB2p0_PHY_driver.sv"

	`include "../agents/host_controller_agent/USB2p0_HOST_controller_monitor.sv"
	`include "../agents/device_controller_agent/USB2p0_DEVICE_controller_monitor.sv"
	`include "../agents/phy_agent/USB2p0_PHY_monitor.sv"

        `include "../sequences/virtual_sequencer/usb2p0_base_virtual_sequencer.sv"
        `include "../sequences/virtual_sequence/usb2p0_base_virtual_sequence.sv"
	
        `include "../agents/host_controller_agent/USB2p0_HOST_controller_agent.sv"
	`include "../agents/phy_agent/USB2p0_PHY_agent.sv"
	`include "../agents/device_controller_agent/USB2p0_DEVICE_controller_agent.sv"

	`include "../sequences/host_sequences/USB2p0_HOST_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_HOST_LS_detect_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_setup_data_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_data_stage_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_set_address_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_clear_feature_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_set_configuration_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_set_feature_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_set_interface_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_ep1_set_configuration_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_get_configuration_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_get_interface_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_get_status_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_ct_get_descriptor_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_interrupt_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_ls_interrupt_out_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_ct_set_configuration_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_ct_set_interface_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_ct_get_configuration_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_ct_get_descriptor_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_ct_get_interface_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_isochronous_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_isochronous_out_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_interrupt_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_interrupt_out_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_bulk_in_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_host_fs_bulk_out_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_HOST_LS_token_pkt_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_HOST_FS_detect_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_HOST_HS_detect_sequence.sv"
	`include "../sequences/host_sequences/USB2p0_HOST_vbus_connect_sequence.sv"
	`include "../sequences/host_sequences/USB2p0_HOST_vbus_disconnect_sequence.sv"
	`include "../sequences/host_sequences/usb2p0_fs_ctrl_trans_get_descriptor_seq.sv"

	`include "../sequences/phy_sequences/USB2p0_PHY_sequence.sv"
	`include "../sequences/phy_sequences/USB2p0_PHY_vbus_sequence.sv"
	`include "../sequences/phy_sequences/USB2p0_PHY_LS_detect_sequence.sv"
	`include "../sequences/phy_sequences/USB2p0_PHY_LS_data_stage_sequence.sv"
	`include "../sequences/phy_sequences/USB2p0_PHY_FS_detect_sequence.sv"
	`include "../sequences/phy_sequences/USB2p0_PHY_HS_detect_sequence.sv"

	`include "../sequences/device_sequences/USB2p0_DEVICE_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_vbus_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_LS_detect_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_ls_setup_hs_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_ls_send_hs_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_token_pkt_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_FS_detect_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_HS_detect_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_fs_send_hs_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_fs_setup_sequence.sv"
	`include "../sequences/device_sequences/USB2p0_DEVICE_DESCRIPTOR_FS_sequence.sv"
	//`include "../sequences/device_sequences/USB2p0_DEVICE_DESCRIPTOR_LS_sequence.sv"

	//------------------ adding vsequences ------------------------//
        `include "../sequences/virtual_sequence/usb2p0_vbus_connect_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_vbus_disconnect_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_detect_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_setup_data_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_set_address_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_clear_feature_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_set_configuration_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_ep1_set_configuration_vsequence.sv" //not using
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_set_feature_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_set_interface_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_control_transfer_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_get_configuration_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_get_interface_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_get_status_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_ct_get_descriptor_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ct_set_configuration_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ct_set_interface_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ct_get_configuration_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ct_get_descriptor_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ct_get_interface_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_isochronous_in_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_isochronous_out_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_interrupt_in_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_interrupt_out_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_interrupt_in_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_bulk_in_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_bulk_out_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_ls_interrupt_out_vsequence.sv"
        `include "../sequences/virtual_sequence/usb2p0_fs_ctrl_trans_get_descriptor_vsequence.sv"

	//-------------------------------------------------------------//
        `include "../env/USB2p0_scoreboard.sv"
        `include "../env/usb2p0_subscriber.sv"
        `include "../env/USB2p0_environment.sv"

        `include "../tests/USB2p0_base_test.sv"
        `include "../tests/USB2p0_vbus_connect_test.sv"
        `include "../tests/USB2p0_vbus_disconnect_test.sv"
        //`include "../tests/USB2p0_LS_ct_setup_data_test.sv"
        `include "../tests/USB2p0_LS_CT_set_address_test.sv"
        `include "../tests/USB2p0_LS_CT_clear_feature_test.sv"
        `include "../tests/USB2p0_LS_CT_set_configuration_test.sv"
        `include "../tests/USB2p0_LS_CT_set_feature_test.sv"
        `include "../tests/USB2p0_LS_CT_set_interface_test.sv"
        `include "../tests/USB2p0_LS_CT_get_configuration_test.sv"
        `include "../tests/USB2p0_LS_CT_get_interface_test.sv"
        `include "../tests/USB2p0_LS_CT_get_status_test.sv"
        `include "../tests/USB2p0_LS_CT_get_descriptor_test.sv"
        `include "../tests/USB2p0_LS_interrupt_in_test.sv"
        `include "../tests/USB2p0_LS_interrupt_out_test.sv"
        `include "../tests/USB2p0_LS_detect_test.sv"
        `include "../tests/usb2p0_ls_control_transfer_test.sv"
        `include "../tests/USB2p0_FS_isochronous_in_test.sv"
        `include "../tests/USB2p0_FS_isochronous_out_test.sv"
        `include "../tests/USB2p0_FS_CT_set_configuration_test.sv"
        `include "../tests/USB2p0_FS_CT_set_interface_test.sv"
        `include "../tests/USB2p0_FS_CT_get_configuration_test.sv"
        `include "../tests/USB2p0_FS_CT_get_descriptor_test.sv"
        `include "../tests/USB2p0_FS_CT_get_interface_test.sv"
        `include "../tests/USB2p0_FS_interrupt_in_test.sv"
        `include "../tests/USB2p0_FS_bulk_in_test.sv"
        `include "../tests/USB2p0_FS_bulk_out_test.sv"
        `include "../tests/USB2p0_FS_interrupt_out_test.sv"
        `include "../tests/USB2p0_FS_detect_test.sv"
        `include "../tests/usb2p0_fs_ctrl_trans_get_descriptors_test.sv"
        `include "../tests/USB2p0_HS_detect_test.sv"


endpackage
